# Generated by Django 2.2 on 2021-04-23 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('art_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=70)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('art_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_comments', to='artOff.Art')),
                ('user_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_comment', to='artOff.User')),
            ],
        ),
        migrations.AddField(
            model_name='art',
            name='user_art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_art', to='artOff.User'),
        ),
        migrations.AddField(
            model_name='art',
            name='user_likes',
            field=models.ManyToManyField(related_name='liked_post', to='artOff.User'),
        ),
    ]
