# Generated by Django 2.2 on 2021-04-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artOff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qoute',
            field=models.CharField(default='change me', max_length=300),
        ),
    ]
