# Generated by Django 2.2 on 2021-04-27 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artOff', '0002_user_qoute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='qoute',
            new_name='quote',
        ),
    ]
