# Generated by Django 2.2 on 2021-04-28 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artOff', '0003_auto_20210427_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='quote',
            new_name='qoute',
        ),
    ]
