# Generated by Django 2.2 on 2021-04-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artOff', '0005_auto_20210427_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='default = 00/00/0000'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='default = 00/00/0000'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
